---
- name: restart wireguard
  systemd:
    name: wg-quick@wg0
    state: restarted

- name: restart hostapd
  systemd:
    name: hostapd
    state: restarted

- name: restart dnsmasq
  systemd:
    name: dnsmasq
    state: restarted

- name: restart networking
  shell: |
    ip addr flush dev {{ wireless_interface }}
    ip addr add {{ ap_ip }}/24 dev {{ wireless_interface }}
    ip link set {{ wireless_interface }} up

- name: apply sysctl
  command: sysctl -p /etc/sysctl.d/99-vpn-router.conf

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart avahi
  systemd:
    name: avahi-daemon
    state: restarted